### ISSUE TITLE
crash on osx 10.14.4

### ISSUE THREAD

**Issue by maddanio** [mbauhardt/keychain2pass#1]
installed scala via homebrew:
```
MacBook-Pro-3:~ daniel$ scala Downloads/keychain2pass_2.12-0.1.2.jar -enc UTF-8
Exception in thread "main" java.lang.BootstrapMethodError: java.lang.NoClassDefFoundError: scala/Serializable
	at com.github.mbauhardt.k2p.Main$.main(Main.scala:19)
	at com.github.mbauhardt.k2p.Main.main(Main.scala)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at scala.reflect.internal.util.ScalaClassLoader.$anonfun$run$2(ScalaClassLoader.scala:105)
	at scala.reflect.internal.util.ScalaClassLoader.asContext(ScalaClassLoader.scala:40)
	at scala.reflect.internal.util.ScalaClassLoader.asContext$(ScalaClassLoader.scala:37)
	at scala.reflect.internal.util.ScalaClassLoader$URLClassLoader.asContext(ScalaClassLoader.scala:130)
	at scala.reflect.internal.util.ScalaClassLoader.run(ScalaClassLoader.scala:105)
	at scala.reflect.internal.util.ScalaClassLoader.run$(ScalaClassLoader.scala:97)
	at scala.reflect.internal.util.ScalaClassLoader$URLClassLoader.run(ScalaClassLoader.scala:130)
	at scala.tools.nsc.CommonRunner.run(ObjectRunner.scala:29)
	at scala.tools.nsc.CommonRunner.run$(ObjectRunner.scala:28)
	at scala.tools.nsc.JarRunner$.run(MainGenericRunner.scala:17)
	at scala.tools.nsc.CommonRunner.runAndCatch(ObjectRunner.scala:35)
	at scala.tools.nsc.CommonRunner.runAndCatch$(ObjectRunner.scala:34)
	at scala.tools.nsc.JarRunner$.runJar(MainGenericRunner.scala:17)
	at scala.tools.nsc.MainGenericRunner.runTarget$1(MainGenericRunner.scala:76)
	at scala.tools.nsc.MainGenericRunner.run$1(MainGenericRunner.scala:91)
	at scala.tools.nsc.MainGenericRunner.process(MainGenericRunner.scala:102)
	at scala.tools.nsc.MainGenericRunner$.main(MainGenericRunner.scala:107)
	at scala.tools.nsc.MainGenericRunner.main(MainGenericRunner.scala)
Caused by: java.lang.NoClassDefFoundError: scala/Serializable
	... 24 more
Caused by: java.lang.ClassNotFoundException: scala.Serializable
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 24 more
MacBook-Pro-3:~ daniel$ 
```

**Comment by jakajancar** [comment]
You have a too new scala version.

    brew install scala@2.12

then

    PATH="/usr/local/opt/scala@2.12/bin:$PATH" scala keychain2pass_2.12-0.1.2.jar -enc UTF-8

**Comment by mbauhardt** [comment]
@maddanio 
sorry for the huge delay? I believe the question is too late, but I will ask anyway.
Is your issue solved?
